apiVersion: v1
kind: Service
metadata:
  name: rest-service
  labels:
   run: rest-service-new
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 8000
    protocol: TCP
  selector:
    run: rest-service
